version: '3'

services:
  db:
    restart: always
    container_name: fs_db
    image: postgres:alpine
    ports:
      - "5412:5432"
    volumes:
      - fs-db:/var/lib/postgresql/data
  redis:
    restart: always
    container_name: fs_redis
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - fs-redis:/data
  web:
    restart: always
    container_name: fs_web
    build: .
    command: ash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn -w 5 front_soup.wsgi --timeout=500 -b 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    user: "1000:1000"
  celery:
    restart: always
    container_name: fs_celery
    build: .
    command: celery -A front_soup worker -l debug
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    user: "1000:1000"
  celery-beat:
    restart: always
    container_name: fs_celery_beat
    build: .
    command: celery -A front_soup beat -l debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
        #user: "1000:1000"
  nginx:
    image: nginx:alpine
    container_name: fs_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static
    depends_on:
      - web

volumes:
  fs-db:
  fs-redis:
