version: '3'

services:
  db:
    restart: always
    container_name: upvnews_db
    image: postgres:11.3
    volumes:
      - upvnews-db:/var/lib/postgresql/data/
  redis:
    restart: always
    container_name: upvnews_redis
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - upvnews-redis:/data
  web:
    restart: always
    container_name: upvnews_web
    build: .
    command: ash -c "python /app/manage.py migrate --noinput && python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    user: "1000:1000"
  celery:
    restart: always
    container_name: upvnews_celery
    build: .
    command: celery -A upvnews worker -l debug
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    user: "1000:1000"
  celery-beat:
    restart: always
    container_name: upvnews_celery_beat
    build: .
    command: celery -A upvnews beat -l debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
        #user: "1000:1000"

volumes:
  upvnews-db:
  upvnews-redis:
