# Generated by Django 2.2.1 on 2019-06-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='path',
            field=models.CharField(default='', max_length=128),
        ),
    ]
